// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXnE0joxKjHTdZf1ybMY_Ueux6NxYwUU',
    appId: '1:548899123568:web:d638e3c10c85b93d31dfb5',
    messagingSenderId: '548899123568',
    projectId: 'iddo-ia',
    authDomain: 'iddo-ia.firebaseapp.com',
    storageBucket: 'iddo-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM0MBfttuzqF8WAKPmcZmXAqsUhTo9cpo',
    appId: '1:548899123568:android:497c8a615f672fe631dfb5',
    messagingSenderId: '548899123568',
    projectId: 'iddo-ia',
    storageBucket: 'iddo-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLTv9cLPX_Hea2U8CgvriYIX8dpWLnKww',
    appId: '1:548899123568:ios:e3c8653ed62ea15f31dfb5',
    messagingSenderId: '548899123568',
    projectId: 'iddo-ia',
    storageBucket: 'iddo-ia.firebasestorage.app',
    iosBundleId: 'com.example.iddoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLTv9cLPX_Hea2U8CgvriYIX8dpWLnKww',
    appId: '1:548899123568:ios:e3c8653ed62ea15f31dfb5',
    messagingSenderId: '548899123568',
    projectId: 'iddo-ia',
    storageBucket: 'iddo-ia.firebasestorage.app',
    iosBundleId: 'com.example.iddoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXnE0joxKjHTdZf1ybMY_Ueux6NxYwUU',
    appId: '1:548899123568:web:b5d5948b6c8ed08631dfb5',
    messagingSenderId: '548899123568',
    projectId: 'iddo-ia',
    authDomain: 'iddo-ia.firebaseapp.com',
    storageBucket: 'iddo-ia.firebasestorage.app',
  );
}
